[package]
name = "mozlz4-tool"
version = "0.1.0"
authors = ["lilydjwg <lilydjwg@gmail.com>"]

[[bin]]
name = "mozlz4cat"
path = "src/main.rs"

[dependencies]
libc = "*"
failure = "*"
byteorder = "*"

[profile.release]
lto = true

