[package]
name = "mozlz4-tool"
version = "0.2.1"
authors = ["lilydjwg <lilydjwg@gmail.com>"]
edition = "2021"

[dependencies]
libc = "*"
eyre = "*"
byteorder = "*"
clap = "*"

[profile.release]
lto = true

